sam.command.new("mmenu")
    :DisallowConsole()
    :SetCategory("Menus")
    :Help("Opens the mantle menu.")
    :DisableNotify(true)
    :OnExecute(function( calling_ply )
        calling_ply:ConCommand("mantle_menu")
    end)
:End()