Lyn.Command("mmenu")
    :DenyConsole()
    :NoConsoleLog()
    :Category("Menus")
    :Help("Opens the mantle menu.")
    :Execute(function( calling_ply )
        calling_ply:ConCommand("mantle_menu")
    end)
:Add()